version: ‘3.7’

services:
  plex:
    image: plexinc/pms-docker
    restart: unless-stopped
    container_name: plexms
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp

    environment:
      - PUID=501
      - PGID=20
      - TZ=America/Chicago
      - PLEX_CLAIM=claim-bBy6zB1ctXjsHpaV_Pu_ # https://www.plex.tv/claim/ (token expires in 4 minutes)
      - HOSTNAME=”PlexServer”
      - ADVERTISE_IP=http://10.0.4.210:32400/ # IP of host running docker

    volumes:
      - ~/Local/Docker/plexms/config:/config
      - ~/Local/Docker/plexms/transcode:/transcode
      - ~/Local/Docker/plexms/media:/media
