# Connect to local dev db with `psql -h 127.0.0.1 -p 5432 -U postgres`
version: '3.7'
services:
  database:
    container_name: db
    image: postgres:14.0-alpine
    volumes:
      - ./db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DATABASE=postgres
    ports:
      - "5432:5432"
    expose:
      - 5432

  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"
    command: memcached -m 64 -p 11211 -U 0

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
