name: Security
run-name: ${{ github.actor }} is running Security Actions
on: [pull_request]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v3
      - name: debug pwd
        run: pwd
      - name: debug2
        run: cat README.md
      - name: Cusotm check for secret files
        run: ${{ github.workspace }}/osConfig/shell/bin/check_for_pattern.sh . "*README*"
      - name: Install Whispers
        run: sudo pip install whispers
      # Scan repo for secrets
      - name: Run whispers
        run: whispers --config test/whisperConfig.yml --severity BLOCKER,CRITICAL ${{ github.workspace }} > /tmp/scan_output.json
      # Upload Artifacts
      - name: Upload the scan output
        uses: actions/upload-artifact@v3
        with:
          name: scan_results
          path: /tmp/scan_output.json
          retention-days: 7
